version: "3.8"

services:
  browser:
    build: .
    container_name: browser-platform
    ports:
      - "18888:18888"   # API
      - "19825:19825"     # CDP
      - "6080:6080"     # WebUI
      - "5900:5900"     # Remote Debugging
    shm_size: 3gb
    environment:
      BB_DAEMON_HOST: "0.0.0.0"
      NOVNC_TOKEN: "tec"
    restart: unless-stopped
    volumes:
      - /data/bb-browser-api/chrome-profile:/root/.bb-browser/browser/user-data
    networks:
      - browser-platform_net